### ISSUE TITLE
Verbal option "now ago" suffix added

### ISSUE THREAD

**Issue by TekBear** [milowg/GMinder#10]
Thanks for new feature :+1: 

I tested using "verbal" option to speak the events for BOTH "soon" and "now".   I hear soon reminders as "<event1 text> starts in <n> minutes" that's fine.  When I have 2 events (in separate calendars) that occur at same time and  reaches the "now" time I hear:  "\<event1 text\> starts now ago \<event2 text\> starts now ago".  Looks extra "ago" word appended.  Example: [audio](http://1drv.ms/1JCSEHG)
:bulb: A little delay between  <event1 text>  and <event2 text> would be helpful  :wink: 

Update April 27:
The speaking  is done synchronously so delays the window display from completing depending on length text being said. It would be better to execute speaking asynchronously.

**Comment by milowg** [comment]
@TekBear I am working on a fix for this but I don't use the feature, so would you be able to test it for me? Let me know what email address I can send the new app to.

**Comment by TekBear** [comment]
@milowg yes I can. Here is contact info below.
![text - r12 tekbear hotmail com](https://cloud.githubusercontent.com/assets/5044866/13377154/35e329e8-de0a-11e5-9592-b2990092faf5.png)

**Comment by TekBear** [comment]
I have been running the test version you sent me and it works fine.

**Comment by milowg** [comment]
Fixed in latest version 1.4.0.6. Thanks @TekBear for testing this.
