### ISSUE TITLE
REQUEST: Add time to the quick add feature

### ISSUE THREAD

**Issue by diegopau** [milowg/GMinder#16]
Would it be possible to have an option to choose a specific time on the Quick Add window? I never create events that are set for the whole day (the way it is behaving now) so I would have to go to the Google Calendar web interface and change the time!

Thanks a lot for your work

**Comment by milowg** [comment]
You should be able to put the time in the quick add text itself. For example: "Do something at 6pm"

**Comment by diegopau** [comment]
True! Sorry, I didn't know about this feature. I close the issue then. Thanks a lot!
