### ISSUE TITLE
Unable to access %temp%\aaaaaaaa.DLL

### ISSUE THREAD

**Issue by TekBear** [milowg/GMinder#18]
I have been getting an error about 50% of the time I start up GMinder. GMinder fails with the error message below in the attached images. The event log entries are:

 * Event ID:	1026
 * Event ID:	5000 

See details http://pastebin.com/GW6K9YXU

I get a blank window, and the same type of message when I attempt to exit GMinder (see attached), so I have to kill the process and restart it. I think this  a race condition with some random DLL that is being created by GMinder in %TEMP%\aaaaaa.DLL where aaaaaaaa is a random string and the virus scanner looking at when Gminder tries to delete it. 

I just installed Avast anti-virus 2016 free version about the time this started. I made some changes to fix another DLL related [problem](http://www.wilderssecurity.com/threads/ocget-dll.88284/) on my machine which was solved by clearingthe value of key HKLM\...\CodeBaseSearchPath in the registry. Could this be related?

I found a workaround which stops the Gminder startup error occurring by adding an exception rule in the Avast "file system shield" exclusion list for "%TEMP%\*.DLL" so now any DLL created in %TEMP% will not be scanned.  The problem went away but this opens a possible [CVE](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures). It makes it hard to write a explicit exception rule because the DLL changes on every error message.  I will follow this up with Avast support if there is another way to do it.  

Could you tell me why does GMinder make these %TEMP%\aaaaaaaa.DLL using random names it may help me better understand the problem.  Is it a strange behaviour or is this a normal dot net behaviour? Is there any flexibility in the way this works?

![gminder exception1](https://cloud.githubusercontent.com/assets/5044866/11631855/12fedb4a-9d3f-11e5-96f2-d01237cbfc94.png)
![gminder exception2](https://cloud.githubusercontent.com/assets/5044866/11631883/36014164-9d3f-11e5-941f-8aed9f5ad589.png)
![gminder exception3](https://cloud.githubusercontent.com/assets/5044866/11631887/3b3a30c8-9d3f-11e5-93d2-d3c51e8e3035.png)

Platform: XP PRO SP3 + Dot Net 4.0.30319 + GMinder 1.4.0.3

**Comment by milowg** [comment]
This appears to be coming from the XmlSerializer class that GMinder uses to load/save settings. See: https://social.msdn.microsoft.com/Forums/en-US/bdc2d75e-8f08-4f64-bfa2-3be32b509a74/wierd-dll-file-issue-in-net-app?forum=csharpgeneral

There is a way to change this directory to somewhere else, perhaps I can add that feature.

**Comment by TekBear** [comment]
Ok Gil a specific folder eg %TEMP%\gminder  or somewhere in %APPDATA% would be better so I can  write an Avast f exception rule specific to that folder.  

Thank you for that article link. If I understand it correctly other Dot Net applications (although I have none currently) could do the same thing, so if I change "%WINDIR%\Microsoft\.Net Framework\v4.0.30319\Config\machine.config" and add:
> <system.xml.serialization>
>    <xmlSerializer tempFilesLocation="<%TEMP%\dot-net"/>
>  </system.xml.serialization>
would that work using environment var?

**Comment by milowg** [comment]
Yes that's certainly worth a try and is a good stop gap until I can change the temp file in the code. Nice find!

**Comment by milowg** [comment]
Setting this XML file seems to be the only way to fix this issue.
