### ISSUE TITLE
BUG: GMinder does not save or remember last screen location.

### ISSUE THREAD

**Issue by noticz** [milowg/GMinder#2]
I have a hard hack with Autohotkey that I use to keep the screen location the same when I open it but I would rather not have to use it. Can you please fix this, I know it should take only a couple minutes. 

I relied on GMinder so much that I was lost without it so I wanted to say thank you for fixing the API problem. I know you just jumped in and fixed it but I was almost ready to pay someone to do so...My point being is that I want to toss some donation cash your way. Let me know your paypal or setup something on your main website so people can donate.

**Comment by milowg** [comment]
Fixed in latest version (1.4.0.1)

If you'd like to donate, you can do so here:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=D6EVXGZF9Q6A2
