### ISSUE TITLE
GMAIL enabled account

### ISSUE THREAD

**Issue by tvk7** [milowg/GMinder#27]
Hi,

I really like this very elegant tool and appreciate your work. 

Just a question: 
Is it mandatory for this tool to work, that the Google Account has Gmail enabled?
In our environment we use G-Suite with disabled GMail/GDrive (for legal reasons/concerns...)

Thanks,
Thomas

**Comment by tvk7** [comment]
please close

**Comment by milowg** [comment]
Sorry I must have missed this one. I don't think a gmail account is required, but you do need a google account.
