### ISSUE TITLE
Hi, how do I unstall Gminder? Although it seems great I do not have a use for it. Thanks.

### ISSUE THREAD

**Issue by Gobebe** [milowg/GMinder#29]

**Comment by milowg** [comment]
GMinder uses the Windows installer, so just go to add/remove programs and remove it just like any other application.

**Comment by Gobebe** [comment]
Thank you @milowg but the name gminder does not show in there. It doesn't not show in my revo app either. 

![image](https://user-images.githubusercontent.com/32020569/30521986-0d93273a-9b97-11e7-981c-9e2056b7a47a.png)

**Comment by milowg** [comment]
Not sure why it does not show up for you. You can just remove the directory it was installed to, which is most likely under program files

**Comment by Gobebe** [comment]
Thank you!!!
