### ISSUE TITLE
IDP.Alexa.51 Virus Warning. Avast blocking Gminder

### ISSUE THREAD

**Issue by domthew** [milowg/GMinder#31]
IDP.Alexa.51 Virus Warning. Avast is blocking Gminder.exe after trying to open sound or clicking Ok button in Options (i'm not sure which one it was).
![image](https://user-images.githubusercontent.com/44837168/48130058-a3b9e280-e28b-11e8-930c-85ee9d42313b.png)

**Comment by milowg** [comment]
What I would suggest is that you report a false positive with Avast. They have an online form here:
https://www.avast.com/false-positive-file-form.php
