### ISSUE TITLE
GMinder has stopped working

### ISSUE THREAD

**Issue by nomarkeu** [milowg/GMinder#32]
Happened last week. Nothing seems to have changed with the OS. It's windows 8.1. Here's the 'problem details'.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	GMinder.exe
  Problem Signature 02:	1.4.0.8
  Problem Signature 03:	58d58b54
  Problem Signature 04:	System.Xml
  Problem Signature 05:	4.6.1590.0
  Problem Signature 06:	5787eeba
  Problem Signature 07:	b7a
  Problem Signature 08:	27
  Problem Signature 09:	IOIBMURHYNRXKW0ZXKYRVFN0BOYYUFOW
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	0308
  Additional Information 2:	0308170a6aba994e23059673e4f85536
  Additional Information 3:	c7c5
  Additional Information 4:	c7c5dc310f7fe7bdb1f8e61bf6eb73a5

I love this program. So I hope it can be solved somehow.

Thanks.

**Comment by milowg** [comment]
Can you check for an error log file in the following location:
%localappdata%\IsolatedStorage\--\Files\ErrorLog.txt
The -- is a series of randomly named folders specific to your machine

**Comment by nomarkeu** [comment]
Here it is.

```
04-09-2018 02:00:41 - Unable to load saved calendars and events
                      There is an error in XML document (0, 0).
  Root element is missing.

17-10-2018 04:13:56 - An error occurred while sending the request.
  The remote name could not be resolved: 'www.googleapis.com'

22-10-2018 01:21:21 - An error occurred while sending the request.
  The remote name could not be resolved: 'www.googleapis.com'

22-10-2018 02:46:36 - Unable to load saved calendars and events
                      There is an error in XML document (0, 0).
  Root element is missing.

22-10-2018 03:48:04 - An error occurred while sending the request.
  The remote name could not be resolved: 'accounts.google.com'

23-10-2018 11:26:12 - An error occurred while sending the request.
  The remote name could not be resolved: 'www.googleapis.com'

24-10-2018 05:21:30 - An error occurred while sending the request.
  The remote name could not be resolved: 'accounts.google.com'

26-10-2018 02:36:37 - A task was canceled.

```

**Comment by milowg** [comment]
Seems like two issues: can't load the xml file that stores settings and can't connect to Google's servers. Can you try to connect to accounts.google.com in a browser and see what it says? You can also try to remove the %appdata%\Gminder folder and re-run GMinder.

**Comment by nomarkeu** [comment]
> Can you try to connect to accounts.google.com in a browser and see what it says?

It works. Goes to https://myaccount.google.com/?pli=1.

> You can also try to remove the %appdata%\Gminder folder and re-run GMinder.

Tried it . Still doesn't work.

**Comment by nomarkeu** [comment]
So I got a solution. I downloaded the binaries and extracted it to a folder. Works! It doesn't work if I install it.

http://www.milow.net/public/dl.php?id=31&rel=GMinder+1.4.0.8+Binaries

Set it up and it sits pretty in my system tray. Thanks for your help!
