### ISSUE TITLE
Cannot access a disposed object message

### ISSUE THREAD

**Issue by TekBear** [milowg/GMinder#6]
I know GMinder has always had a few glitches -  I got this one and not a high priority.

To produce error:
1. add events 8 mins into future via web browser with reminders set for 5 at 10mins before event
2. restart GMINDER 
3. wait 2 seconds, click on system tray icon leave pop up open and do nothing, wait 5 mins
5. Got an exception message see attached when pop up is on screen and a reminder time or event time is reached. The GMinder window is displayed (the one iwth Hide/snooze buttons) as well. It is not a big deal just  press continue and everything seemed ok. 

![gminder agenda exception](https://cloud.githubusercontent.com/assets/5044866/7218965/345184da-e6bc-11e4-9ecb-d025186554f9.png)
Full error text see  http://pastebin.com/U3aNhdQn

**Comment by milowg** [comment]
Fixed in 1.4.0.2 available on download site
