### ISSUE TITLE
BUG: Deleting or moving event via web browser does not update on Gminder

### ISSUE THREAD

**Issue by noticz** [milowg/GMinder#8]
I am scared to click on the clear events but I am having an issue where I delete the event or move it to a new calendar and it does not update on Gminder.

**Comment by TekBear** [comment]
"Clear events" erase the ENTIRE contents of the GMinder window - not quite sure if it always did that IIRC I think it meant "clear past events".  "refresh events" does not rebuild  the main window (=double mouse click),  although it does rebuld pop-up window (=single mouse click). Restarting GMinder after choosing "Clear events" option will reload all your future events or you could choose "download" on calendar selection window.

I always restart GMinder whenever I move events on calendar or delete event in browser.  The GMinder context menu "refresh events" option does not process changed events correctly. If you move an event to a new day and don't change time it works fine. If event time is changed it does not update it in main window (see attachment below).  New events are ok they get added to window. First image shows details are correct (12:30am) but still has old time (1 am).

![gminder after event refrresh](https://cloud.githubusercontent.com/assets/5044866/7323602/5047b608-eae2-11e4-855e-3fbe7f33d169.png)

After restart the time in main window time is correct.

![gminder - after restart](https://cloud.githubusercontent.com/assets/5044866/7323622/895a145e-eae2-11e4-9269-1fff98738b82.png)

**Comment by noticz** [comment]
Sweet, yeah that seemed to work...Thanks man. I also am glad to see your using GMinder extensively like I am. Hope you got my donation from a couple days ago.

**Comment by noticz** [comment]
But I would rather not have to clear and update every time I change something and this also reloads all the calendar alerts that I had dismissed...so I am keeping this open.

**Comment by noticz** [comment]
I think the new version with the using the google ID fixed this issue.
