### ISSUE TITLE
REQUEST: Add the current date to the quick add title or a clickable calendar icon

### ISSUE THREAD

**Issue by noticz** [milowg/GMinder#9]
I have a hard time knowing what date it is, would be nice to just have it have the date in the title or somewhere on the quick add window. I find myself having to look up the date every time I add something. Or even better yet have a calendar on there or an option checkbox that gives a little calendar icon that is clickable on the window somewhere.

So you can type:
Meeting with brad at 6pm, click calendar icon and it will put in the date for you once you select what date.

I know it is just as easy sometimes to put "Meeting with brad 6pm next Monday" but only if you know what date correlates to the Monday.

**Comment by TekBear** [comment]
I don't use quick add in GMinder but that sounds like a good feature for those that do. While you waiting you could use one of these tools to just pop up a calendar real quick via one click:

TCLOCKEX:
![tclockex v1 4 date popup](https://cloud.githubusercontent.com/assets/5044866/7329129/a902c888-eb0e-11e4-8644-c60a05cf6472.jpg)

GREATIS TOY:
![geatistoys - calendar pop up](https://cloud.githubusercontent.com/assets/5044866/7329131/aea06c78-eb0e-11e4-8eb3-4cd2404218d5.jpg)

Freeware and works WIN XP I don't know will run on latter  OS versions

**Comment by noticz** [comment]
Seems like some good tools but I think I will wait, I still have a one click on the bottom taskbar on the time to show the calendar. Thanks for the info and idea though.

**Comment by milowg** [comment]
Done in 1.4.0.2 available on download site
